"""new model using request

Revision ID: 84d95f0415d3
Revises: 337994a613f4
Create Date: 2024-08-04 18:14:31.665064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d95f0415d3'
down_revision: Union[str, None] = '337994a613f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('property_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'property_id')
    # ### end Alembic commands ###
