"""initial migration

Revision ID: 8a185454600e
Revises: 4aec9dd41664
Create Date: 2024-08-04 17:34:16.113311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8a185454600e'
down_revision: Union[str, None] = '4aec9dd41664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('local_ip', sa.String(), nullable=False),
    sa.Column('primary_ip', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('additional_price', sa.JSON(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.drop_table('houses-vivareal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses-vivareal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.VARCHAR(), nullable=False),
    sa.Column('additional_price', sqlite.JSON(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('properties', sqlite.JSON(), nullable=False),
    sa.Column('house_type', sa.VARCHAR(), nullable=False),
    sa.Column('images', sqlite.JSON(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('published_at', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('properties')
    # ### end Alembic commands ###
